config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
    resources :posts, only: [:index, :show, :destroy, :edit] 
    resources :comments, only: [:index, :destroy]
    resources :groups, only: [:index, :destroy]
  end

  scope module: :public do
    devise_for :users, controllers: {
      sessions: 'public/sessions',
      registrations: 'public/registrations', 
      passwords: 'public/passwords'
    }
  
    root to: "homes#top"
  
    get 'homes/about' => 'homes#about', as: 'about'
    get 'homes/top' => 'homes#top'
    get 'searches', to: 'searches#search', as: 'search' 
    get '/users/check', to: 'users#check', as: 'users_check'
    patch '/users/withdraw', to: 'users#withdraw', as: 'withdraw_user'

    resources :groups, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resource :permits, only: [:create, :destroy] 
      resource :group_memberships, only: [:create, :destroy]
      get "join" => "groups#join"
    end
    get "groups/:id/permits", to: "groups#permits", as: :permits
    
    resources :posts, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
      resources :comments, only: [:create, :destroy]
      resource :likes, only: [:create, :destroy]
      collection do
        get 'tag_search', to: 'searches#search'
      end
    end

    get '/users/:name', to: 'users#show', as: 'user_show_by_name'
    get '/users/:user_name/edit', to: 'users#edit', as: 'edit_user_by_name'
   
    resources :users, only: [:show, :edit, :update, :destroy] do
      resources :posts, only: [:index]
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/castle.rb
class Castle < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
end

app/models/group.rb
class Group < ApplicationRecord
  
  belongs_to :owner, class_name: 'User'
  has_many :group_membership, dependent: :destroy
  has_many :users, through: :group_membership
  has_many :permits, dependent: :destroy

  validates :group_name, presence: true, length: { maximum: 30 }
  validates :group_introduction, presence: true, length: { maximum: 300 }
  has_one_attached :image

  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
  
end

app/models/like.rb
class Like < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: {scope: :post_id}
  
end

app/models/permit.rb
class Permit < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :tagmaps, dependent: :destroy
  has_many :tags, through: :tagmaps
  
  def favorited_by?(user)
    likes.exists?(user_id: user.id)
  end
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/not_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def self.looks(search, castle_name)
    Post.where("castle_name LIKE ?", "%#{castle_name}%")
  end
  
 def self.posts_serach(search)
   Post.where(['title LIKE ? OR content LIKE ?', "%#{search}%", "%#{search}%"])
 end

 def save_posts(tags)
   current_tags = self.tags.pluck(:tag_name) unless self.tags.nil?
   old_tags = current_tags - tags
   new_tags = tags - current_tags

   # Destroy
    old_tags.each do |old|
      tag = Tag.find_by(tag_name: old)
      self.tags.delete(tag) if tag.present? # nilチェックを追加
    end

   # Create
   new_tags.each do |new_name|
     post_tag = Tag.find_or_create_by(tag_name:new_name)
     self.tags << post_tag
   end
 end
  
end

app/models/tag.rb
class Tag < ApplicationRecord
  
  has_many :tagmaps, dependent: :destroy
  has_many :posts, through: :tagmaps
  
  def self.search(search)
    if search != '#'
      tag = Tag.where(name: search)
      tag[0].posts
    else
      Post.all
    end
  end
  
end

app/models/tagmap.rb
class Tagmap < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :group_membership, dependent: :destroy
  has_many :groups, through: :group_membership
  has_many :permits, dependent: :destroy
  
  has_one_attached :profile_image
  attr_accessor :remove_profile_image
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def self.looks(search, name)
    User.where("name LIKE ?", "%#{name}%")
  end
  
  def active_for_authentication?
    super && (is_active == true)
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/base_helper.rb
module BaseHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/group_helper.rb
module GroupHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin - Sirogram</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
      <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
          <a class="navbar-brand p-3" href="/homes/top" >
            <h1 style="font-family: 'Impact', sans-serif; font-size: 30px; color: white; margin: 0; ">Sirogram</h1>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to 'ダッシュボード', admin_dashboards_path, class: "nav-link text-light"%>
                </li>
                <li class="nav-item">
                  <%= link_to 'コメント一覧', admin_comments_path, class: "nav-link text-light"%>
                </li>
                <li class="nav-item">
                  <%= link_to 'グループ一覧', admin_groups_path, class: "nav-link text-light"%>
                </li>
                <li class="nav-item">
                    <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, data: { confirm: 'ログアウトしてよろしいですか？' } , class: "nav-link text-light" %>
                </li>
              <% end %>
            </ul>
          </div>
      </nav>
    </header>
    <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Sirogram</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

          <a class="navbar-brand p-3" href="/homes/top" >
            <h1 style="font-family: 'Impact', sans-serif; font-size: 30px; color: white; margin: 0; ">Sirogram</h1>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                  aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to '投稿一覧', posts_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to '新規投稿', new_post_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <% if current_user && current_user.name.present? %>
                    <%= link_to 'マイページ', user_show_by_name_path(current_user.name), class: 'nav-link text-light' %>
                  <% end %>
                </li>
                
              <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-light' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-light' %>
                </li>
              <% end %>
            </ul>
          </div>

      </nav>
    </header>
      <%= yield %>
  </body>
</html>